name: studanky_flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_map: ^8.2.2
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.2.1
  go_router: ^14.1.4
  json_annotation: ^4.9.0
  latlong2: ^0.9.1
  logger: ^2.3.0
  mobile_scanner: ^7.1.2

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - lib/core/assets/
